print("Welcome to the tip calculator!")
bill = float(input("What was the total bill? $"))
tip = int(input("What percentage tip would you like to give? 10 12 15 "))
people = int(input("How many people to split the bill? "))
bill_and_tip=bill+(bill*tip/100)
each_person_bill=round(bill_and_tip/people,2)
print(f"Your final tip is {each_person_bill}")
